package tarea01apg;

import java.text.NumberFormat;
import javax.swing.JOptionPane;
import javax.swing.JTextField;
import javax.swing.text.NumberFormatter;

/**
 *
 * @author andres
 */
public class FormNuevaBicicleta extends javax.swing.JDialog {

    /**
     * Creates new form FormNuevaBicicleta
     */
    public FormNuevaBicicleta(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        grupoBotonesTipo = new javax.swing.ButtonGroup();
        panelPrincipal = new javax.swing.JPanel();
        etiquetaCodigo = new javax.swing.JLabel();
        campoTextoCodigo = new javax.swing.JTextField();
        etiquetaModelo = new javax.swing.JLabel();
        campoTextoModelo = new javax.swing.JTextField();
        labelTitulo = new javax.swing.JLabel();
        campoTextoMarca = new javax.swing.JTextField();
        etiquetaMarca = new javax.swing.JLabel();
        panelTipo = new javax.swing.JPanel();
        etiquetaTipo = new javax.swing.JLabel();
        radioBotonTrail = new javax.swing.JRadioButton();
        labelTamanioRuedasTrail = new javax.swing.JLabel();
        comboboxTamanioRueda = new javax.swing.JComboBox<>();
        labelMaterialCuadroTrail = new javax.swing.JLabel();
        comboboxMaterialCuadroTrail = new javax.swing.JComboBox<>();
        radioBotonCrossCountry = new javax.swing.JRadioButton();
        radioBotonDescenso = new javax.swing.JRadioButton();
        radioBotonFatBike = new javax.swing.JRadioButton();
        radioBotonCarretera = new javax.swing.JRadioButton();
        labelMaterialCuadroCarretera = new javax.swing.JLabel();
        comboboxMaterialCuadroCarretera = new javax.swing.JComboBox<>();
        labelMaterialCuadroCarretera1 = new javax.swing.JLabel();
        comboboxMaterialCuadroCarretera1 = new javax.swing.JComboBox<>();
        etiquetaProveedor = new javax.swing.JLabel();
        etiquetaFechaAlta = new javax.swing.JLabel();
        etiquetaTelefonoContacto = new javax.swing.JLabel();
        campoTextoProveedor = new javax.swing.JFormattedTextField();
        campoTextoTelefonoContacto = new javax.swing.JFormattedTextField();
        campoTextoPrecioCoste = new javax.swing.JFormattedTextField();
        etiquetaPrecioCoste = new javax.swing.JLabel();
        botonGuardar = new javax.swing.JButton();
        botonSalir = new javax.swing.JButton();
        spinnerFechaAlta = new javax.swing.JSpinner();
        panelUbicacionPVP = new javax.swing.JPanel();
        etiquetaUbicacion = new javax.swing.JLabel();
        comboboxUbicacion = new javax.swing.JComboBox<>();
        etiquetaPVP = new javax.swing.JLabel();
        campoTextoPVP = new javax.swing.JFormattedTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Formulario para añadir bicicleta");

        panelPrincipal.setBackground(new java.awt.Color(153, 0, 153));
        panelPrincipal.setToolTipText("selecciona el tipo de bicicleta");

        etiquetaCodigo.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        etiquetaCodigo.setForeground(new java.awt.Color(0, 0, 0));
        etiquetaCodigo.setText("Código:");
        etiquetaCodigo.setToolTipText("Codigo de la bicicleta");

        campoTextoCodigo.setToolTipText("Introduce el código de la bicicleta");

        etiquetaModelo.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        etiquetaModelo.setForeground(new java.awt.Color(0, 0, 0));
        etiquetaModelo.setText("Modelo:");
        etiquetaModelo.setToolTipText("Modelo de la bicicleta");

        campoTextoModelo.setToolTipText("Introduce el modelo la bicicleta");

        labelTitulo.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        labelTitulo.setForeground(new java.awt.Color(0, 0, 0));
        labelTitulo.setText("Añadir nueva bicicleta");
        labelTitulo.setToolTipText("Formulario para añadir una bicicleta");

        campoTextoMarca.setToolTipText("Introduce la marca de la bicicleta");

        etiquetaMarca.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        etiquetaMarca.setForeground(new java.awt.Color(0, 0, 0));
        etiquetaMarca.setText("Marca:");
        etiquetaMarca.setToolTipText("Marca de la bicicleta");

        panelTipo.setBackground(new java.awt.Color(153, 0, 153));
        panelTipo.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.LOWERED, new java.awt.Color(153, 153, 153), new java.awt.Color(153, 153, 153), new java.awt.Color(153, 153, 153), new java.awt.Color(153, 153, 153)));

        etiquetaTipo.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        etiquetaTipo.setForeground(new java.awt.Color(0, 0, 0));
        etiquetaTipo.setText("Tipo:");
        etiquetaTipo.setToolTipText("Tipo de bicicleta");

        radioBotonTrail.setBackground(new java.awt.Color(153, 0, 153));
        grupoBotonesTipo.add(radioBotonTrail);
        radioBotonTrail.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        radioBotonTrail.setForeground(new java.awt.Color(0, 0, 0));
        radioBotonTrail.setText("Trail");
        radioBotonTrail.setToolTipText("Selecciona tipo de bicicleta trail");
        radioBotonTrail.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                radioBotonTrailActionPerformed(evt);
            }
        });

        labelTamanioRuedasTrail.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        labelTamanioRuedasTrail.setForeground(new java.awt.Color(0, 0, 0));
        labelTamanioRuedasTrail.setText("Tamaño de ruedas:");
        labelTamanioRuedasTrail.setToolTipText("Tamaño de ruedas en pulgadas");

        comboboxTamanioRueda.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "26''", "27.5''", "29''" }));
        comboboxTamanioRueda.setToolTipText("Selecciona el tamaño de las ruedas");

        labelMaterialCuadroTrail.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        labelMaterialCuadroTrail.setForeground(new java.awt.Color(0, 0, 0));
        labelMaterialCuadroTrail.setText("Material del cuadro:");
        labelMaterialCuadroTrail.setToolTipText("Material del cuadro de bicicleta tipo Trail");

        comboboxMaterialCuadroTrail.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Aluminio", "Carbono" }));
        comboboxMaterialCuadroTrail.setToolTipText("Selecciona el material del cuadro de la bicicleta tipo Trail");

        radioBotonCrossCountry.setBackground(new java.awt.Color(153, 0, 153));
        grupoBotonesTipo.add(radioBotonCrossCountry);
        radioBotonCrossCountry.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        radioBotonCrossCountry.setForeground(new java.awt.Color(0, 0, 0));
        radioBotonCrossCountry.setText("Cross country");
        radioBotonCrossCountry.setToolTipText("Selecciona tipo de bicicleta cross country");
        radioBotonCrossCountry.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                radioBotonCrossCountryActionPerformed(evt);
            }
        });

        radioBotonDescenso.setBackground(new java.awt.Color(153, 0, 153));
        grupoBotonesTipo.add(radioBotonDescenso);
        radioBotonDescenso.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        radioBotonDescenso.setForeground(new java.awt.Color(0, 0, 0));
        radioBotonDescenso.setText("Descenso");
        radioBotonDescenso.setToolTipText("Selecciona tipo de bicicleta de descenso");

        radioBotonFatBike.setBackground(new java.awt.Color(153, 0, 153));
        grupoBotonesTipo.add(radioBotonFatBike);
        radioBotonFatBike.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        radioBotonFatBike.setForeground(new java.awt.Color(0, 0, 0));
        radioBotonFatBike.setText("Fat Bike");
        radioBotonFatBike.setToolTipText("Selecciona tipo de bicicleta Fat Bike");
        radioBotonFatBike.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                radioBotonFatBikeActionPerformed(evt);
            }
        });

        radioBotonCarretera.setBackground(new java.awt.Color(153, 0, 153));
        grupoBotonesTipo.add(radioBotonCarretera);
        radioBotonCarretera.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        radioBotonCarretera.setForeground(new java.awt.Color(0, 0, 0));
        radioBotonCarretera.setText("Carretera");
        radioBotonCarretera.setToolTipText("Selecciona tipo de bibicleta de carretera");
        radioBotonCarretera.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                radioBotonCarreteraActionPerformed(evt);
            }
        });

        labelMaterialCuadroCarretera.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        labelMaterialCuadroCarretera.setForeground(new java.awt.Color(0, 0, 0));
        labelMaterialCuadroCarretera.setText("Material del cuadro:");
        labelMaterialCuadroCarretera.setToolTipText("Material del cuadro de bicicleta de carretera");

        comboboxMaterialCuadroCarretera.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Aluminio", "Carbono" }));
        comboboxMaterialCuadroCarretera.setToolTipText("Selecciona el material del cuadro de la bicicleta de carretera");

        labelMaterialCuadroCarretera1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        labelMaterialCuadroCarretera1.setForeground(new java.awt.Color(0, 0, 0));
        labelMaterialCuadroCarretera1.setText("Tipo de freno:");
        labelMaterialCuadroCarretera1.setToolTipText("Tipo de freno de bicicleta tipo carretera");

        comboboxMaterialCuadroCarretera1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Frenos de disco", "Pastillas de freno" }));
        comboboxMaterialCuadroCarretera1.setToolTipText("Selecciona tipo de frenos de bicicleta tipo carretera");

        javax.swing.GroupLayout panelTipoLayout = new javax.swing.GroupLayout(panelTipo);
        panelTipo.setLayout(panelTipoLayout);
        panelTipoLayout.setHorizontalGroup(
            panelTipoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelTipoLayout.createSequentialGroup()
                .addGroup(panelTipoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelTipoLayout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(panelTipoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(panelTipoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(radioBotonDescenso, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(radioBotonFatBike, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(radioBotonCarretera, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(radioBotonCrossCountry)
                            .addComponent(radioBotonTrail, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(etiquetaTipo)))
                    .addGroup(panelTipoLayout.createSequentialGroup()
                        .addGap(55, 55, 55)
                        .addComponent(labelTamanioRuedasTrail)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(comboboxTamanioRueda, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(labelMaterialCuadroTrail)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(comboboxMaterialCuadroTrail, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(panelTipoLayout.createSequentialGroup()
                        .addGap(58, 58, 58)
                        .addComponent(labelMaterialCuadroCarretera)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(comboboxMaterialCuadroCarretera, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(labelMaterialCuadroCarretera1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(comboboxMaterialCuadroCarretera1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        panelTipoLayout.setVerticalGroup(
            panelTipoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelTipoLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(etiquetaTipo)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(radioBotonTrail)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panelTipoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelTamanioRuedasTrail)
                    .addComponent(comboboxTamanioRueda, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(labelMaterialCuadroTrail)
                    .addComponent(comboboxMaterialCuadroTrail, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(radioBotonCrossCountry)
                .addGap(18, 18, 18)
                .addComponent(radioBotonDescenso)
                .addGap(18, 18, 18)
                .addComponent(radioBotonFatBike)
                .addGap(18, 18, 18)
                .addComponent(radioBotonCarretera)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panelTipoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelMaterialCuadroCarretera)
                    .addComponent(comboboxMaterialCuadroCarretera, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(labelMaterialCuadroCarretera1)
                    .addComponent(comboboxMaterialCuadroCarretera1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(27, Short.MAX_VALUE))
        );

        etiquetaProveedor.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        etiquetaProveedor.setForeground(new java.awt.Color(0, 0, 0));
        etiquetaProveedor.setText("Proveedor:");
        etiquetaProveedor.setToolTipText("Proveedor de la bicicleta");

        etiquetaFechaAlta.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        etiquetaFechaAlta.setForeground(new java.awt.Color(0, 0, 0));
        etiquetaFechaAlta.setText("Fecha de alta:");
        etiquetaFechaAlta.setToolTipText("Fecha de alta de la bicicleta");

        etiquetaTelefonoContacto.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        etiquetaTelefonoContacto.setForeground(new java.awt.Color(0, 0, 0));
        etiquetaTelefonoContacto.setText("Teléfono de contacto:");
        etiquetaTelefonoContacto.setToolTipText("Teléfono de contacto");

        campoTextoProveedor.setToolTipText("Introduce el proveedor de la bicicleta");
        campoTextoProveedor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                campoTextoProveedorActionPerformed(evt);
            }
        });

        campoTextoTelefonoContacto.setToolTipText("Introduce un teléfono de contacto");
        campoTextoTelefonoContacto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                campoTextoTelefonoContactoActionPerformed(evt);
            }
        });
        campoTextoTelefonoContacto.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                campoTextoTelefonoContactoKeyTyped(evt);
            }
        });

        campoTextoPrecioCoste.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter()));
        campoTextoPrecioCoste.setToolTipText("Introduce el precio de coste de la bicicleta (máximo 30.000)");
        campoTextoPrecioCoste.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                campoTextoPrecioCosteActionPerformed(evt);
            }
        });
        campoTextoPrecioCoste.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                campoTextoPrecioCosteKeyTyped(evt);
            }
        });

        etiquetaPrecioCoste.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        etiquetaPrecioCoste.setForeground(new java.awt.Color(0, 0, 0));
        etiquetaPrecioCoste.setText("Precio de coste (€):");
        etiquetaPrecioCoste.setToolTipText("Precio de coste de la bicicleta");

        botonGuardar.setBackground(new java.awt.Color(0, 153, 0));
        botonGuardar.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        botonGuardar.setForeground(new java.awt.Color(0, 0, 0));
        botonGuardar.setText("Guardar");
        botonGuardar.setToolTipText("Pulsa este boton para almacenar los datos introducidos en el formulario");
        botonGuardar.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(204, 204, 0), 3, true));

        botonSalir.setBackground(new java.awt.Color(204, 0, 0));
        botonSalir.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        botonSalir.setForeground(new java.awt.Color(0, 0, 0));
        botonSalir.setText("Salir");
        botonSalir.setToolTipText("Pulsa este boton para salir del formulario");
        botonSalir.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(204, 204, 0), 3, true));

        spinnerFechaAlta.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        spinnerFechaAlta.setModel(new javax.swing.SpinnerDateModel(new java.util.Date(1728817280839L), null, null, java.util.Calendar.DAY_OF_MONTH));
        spinnerFechaAlta.setToolTipText("Selecciona la fecha de alta de la bicicleta");
        spinnerFechaAlta.setEditor(new javax.swing.JSpinner.DateEditor(spinnerFechaAlta, "dd/mm/yyyy"));

        panelUbicacionPVP.setBackground(new java.awt.Color(153, 0, 153));
        panelUbicacionPVP.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, new java.awt.Color(153, 153, 153), new java.awt.Color(153, 153, 153), new java.awt.Color(153, 153, 153), new java.awt.Color(153, 153, 153)));
        panelUbicacionPVP.setToolTipText("Ubicación y Precio de venta al público");

        etiquetaUbicacion.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        etiquetaUbicacion.setForeground(new java.awt.Color(0, 0, 0));
        etiquetaUbicacion.setText("Ubicación:");
        etiquetaUbicacion.setToolTipText("Ubicación de la bicicleta");

        comboboxUbicacion.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Almacén", "Tienda", "Taller" }));
        comboboxUbicacion.setToolTipText("Selecciona la ubicación de la bicicleta");

        etiquetaPVP.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        etiquetaPVP.setForeground(new java.awt.Color(0, 0, 0));
        etiquetaPVP.setText("P.V.P. (€):");
        etiquetaPVP.setToolTipText("Precio venta al público de la bicicleta");

        campoTextoPVP.setToolTipText("Introduce el precio venta al público de la bicicleta (máximo 30.000)");
        campoTextoPVP.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                campoTextoPVPActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout panelUbicacionPVPLayout = new javax.swing.GroupLayout(panelUbicacionPVP);
        panelUbicacionPVP.setLayout(panelUbicacionPVPLayout);
        panelUbicacionPVPLayout.setHorizontalGroup(
            panelUbicacionPVPLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelUbicacionPVPLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(etiquetaUbicacion)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(comboboxUbicacion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(84, 84, 84)
                .addComponent(etiquetaPVP)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(campoTextoPVP, javax.swing.GroupLayout.PREFERRED_SIZE, 126, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(37, 37, 37))
        );
        panelUbicacionPVPLayout.setVerticalGroup(
            panelUbicacionPVPLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelUbicacionPVPLayout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addGroup(panelUbicacionPVPLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(etiquetaUbicacion)
                    .addComponent(etiquetaPVP)
                    .addComponent(campoTextoPVP, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(comboboxUbicacion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout panelPrincipalLayout = new javax.swing.GroupLayout(panelPrincipal);
        panelPrincipal.setLayout(panelPrincipalLayout);
        panelPrincipalLayout.setHorizontalGroup(
            panelPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelPrincipalLayout.createSequentialGroup()
                .addGap(181, 181, 181)
                .addComponent(labelTitulo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(213, 213, 213))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelPrincipalLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addGroup(panelPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(panelTipo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(panelPrincipalLayout.createSequentialGroup()
                            .addComponent(etiquetaCodigo)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(campoTextoCodigo, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(18, 18, 18)
                            .addComponent(etiquetaModelo)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(campoTextoModelo, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(18, 18, 18)
                            .addComponent(etiquetaMarca)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(campoTextoMarca, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(panelPrincipalLayout.createSequentialGroup()
                        .addGroup(panelPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(panelPrincipalLayout.createSequentialGroup()
                                .addComponent(etiquetaTelefonoContacto)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(campoTextoTelefonoContacto, javax.swing.GroupLayout.PREFERRED_SIZE, 126, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(panelPrincipalLayout.createSequentialGroup()
                                .addComponent(etiquetaFechaAlta)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(spinnerFechaAlta, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(18, 18, 18)
                        .addGroup(panelPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(panelPrincipalLayout.createSequentialGroup()
                                .addComponent(etiquetaPrecioCoste)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(campoTextoPrecioCoste, javax.swing.GroupLayout.PREFERRED_SIZE, 126, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(panelPrincipalLayout.createSequentialGroup()
                                .addComponent(etiquetaProveedor)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(campoTextoProveedor, javax.swing.GroupLayout.PREFERRED_SIZE, 126, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addGap(89, 89, 89))
            .addGroup(panelPrincipalLayout.createSequentialGroup()
                .addGroup(panelPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelPrincipalLayout.createSequentialGroup()
                        .addGap(158, 158, 158)
                        .addComponent(botonGuardar, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(197, 197, 197)
                        .addComponent(botonSalir, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(panelPrincipalLayout.createSequentialGroup()
                        .addGap(87, 87, 87)
                        .addComponent(panelUbicacionPVP, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        panelPrincipalLayout.setVerticalGroup(
            panelPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelPrincipalLayout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addComponent(labelTitulo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(29, 29, 29)
                .addGroup(panelPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(etiquetaCodigo)
                        .addComponent(campoTextoCodigo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(panelPrincipalLayout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 1, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(panelPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(etiquetaModelo)
                            .addComponent(campoTextoModelo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(etiquetaMarca)
                            .addComponent(campoTextoMarca, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(18, 18, 18)
                .addComponent(panelTipo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(23, 23, 23)
                .addGroup(panelPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(etiquetaFechaAlta)
                    .addComponent(etiquetaProveedor)
                    .addComponent(campoTextoProveedor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(spinnerFechaAlta, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(panelPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(etiquetaTelefonoContacto)
                    .addComponent(campoTextoTelefonoContacto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(etiquetaPrecioCoste)
                    .addComponent(campoTextoPrecioCoste, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(panelUbicacionPVP, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(52, 52, 52)
                .addGroup(panelPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(botonGuardar)
                    .addComponent(botonSalir))
                .addGap(37, 37, 37))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelPrincipal, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelPrincipal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void radioBotonFatBikeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_radioBotonFatBikeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_radioBotonFatBikeActionPerformed

    private void radioBotonCarreteraActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_radioBotonCarreteraActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_radioBotonCarreteraActionPerformed

    private void radioBotonTrailActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_radioBotonTrailActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_radioBotonTrailActionPerformed

    private void radioBotonCrossCountryActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_radioBotonCrossCountryActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_radioBotonCrossCountryActionPerformed

    private void campoTextoProveedorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_campoTextoProveedorActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_campoTextoProveedorActionPerformed

    private void campoTextoTelefonoContactoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_campoTextoTelefonoContactoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_campoTextoTelefonoContactoActionPerformed

    private void campoTextoPrecioCosteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_campoTextoPrecioCosteActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_campoTextoPrecioCosteActionPerformed

    private void campoTextoPVPActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_campoTextoPVPActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_campoTextoPVPActionPerformed

    private void campoTextoTelefonoContactoKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_campoTextoTelefonoContactoKeyTyped

        // obtengo el caracter introducido
        char c = evt.getKeyChar();
        // si el carácter no es un número, se ignora
        if (!Character.isDigit(c)) {
            evt.consume(); // evita que el carácter no numérico se introduzca
        }
    }//GEN-LAST:event_campoTextoTelefonoContactoKeyTyped

    private void campoTextoPrecioCosteKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_campoTextoPrecioCosteKeyTyped

        int caracterIntroducido = evt.getKeyChar();

        // Comprobar si es un número
        boolean esNumero = caracterIntroducido >= 48 && caracterIntroducido <= 57;

        if (!esNumero) {
            evt.consume();  // Si no es un número, se cancela la acción
        } else {
            // Obtener el texto actual del campo
            String textoActual = ((JTextField) evt.getSource()).getText();

            // Concatenar el carácter introducido para obtener el valor completo
            String textoConNuevoCaracter = textoActual + evt.getKeyChar();

            try {
                // Convertir el texto a un número entero
                int valorIntroducido = Integer.parseInt(textoConNuevoCaracter);

                // Si el valor es mayor a 30.000, se cancela la acción
                if (valorIntroducido > 30000) {
                    evt.consume();  // No permitir valores mayores a 30.000
                    JOptionPane.showMessageDialog(null, "El valor no puede superar los 30.000 €.");
                }
            } catch (NumberFormatException e) {
                // En caso de error en la conversión, cancelar la acción
                evt.consume();
            }
        }

    }//GEN-LAST:event_campoTextoPrecioCosteKeyTyped

    /**
     * @param args the command line arguments
     */
//    public static void main(String args[]) {
//        /* Set the Nimbus look and feel */
//        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
//        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
//         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
//         */
//        try {
//            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
//                if ("Nimbus".equals(info.getName())) {
//                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
//                    break;
//                }
//            }
//        } catch (ClassNotFoundException ex) {
//            java.util.logging.Logger.getLogger(FormNuevaBicicleta.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (InstantiationException ex) {
//            java.util.logging.Logger.getLogger(FormNuevaBicicleta.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (IllegalAccessException ex) {
//            java.util.logging.Logger.getLogger(FormNuevaBicicleta.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
//            java.util.logging.Logger.getLogger(FormNuevaBicicleta.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        }
//        //</editor-fold>
//
//        /* Create and display the dialog */
//        java.awt.EventQueue.invokeLater(new Runnable() {
//            public void run() {
//                FormNuevaBicicleta dialog = new FormNuevaBicicleta(new javax.swing.JFrame(), true);
//                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
//                    @Override
//                    public void windowClosing(java.awt.event.WindowEvent e) {
//                        System.exit(0);
//                    }
//                });
//                dialog.setVisible(true);
//            }
//        });
//    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton botonGuardar;
    private javax.swing.JButton botonSalir;
    private javax.swing.JTextField campoTextoCodigo;
    private javax.swing.JTextField campoTextoMarca;
    private javax.swing.JTextField campoTextoModelo;
    private javax.swing.JFormattedTextField campoTextoPVP;
    private javax.swing.JFormattedTextField campoTextoPrecioCoste;
    private javax.swing.JFormattedTextField campoTextoProveedor;
    private javax.swing.JFormattedTextField campoTextoTelefonoContacto;
    private javax.swing.JComboBox<String> comboboxMaterialCuadroCarretera;
    private javax.swing.JComboBox<String> comboboxMaterialCuadroCarretera1;
    private javax.swing.JComboBox<String> comboboxMaterialCuadroTrail;
    private javax.swing.JComboBox<String> comboboxTamanioRueda;
    private javax.swing.JComboBox<String> comboboxUbicacion;
    private javax.swing.JLabel etiquetaCodigo;
    private javax.swing.JLabel etiquetaFechaAlta;
    private javax.swing.JLabel etiquetaMarca;
    private javax.swing.JLabel etiquetaModelo;
    private javax.swing.JLabel etiquetaPVP;
    private javax.swing.JLabel etiquetaPrecioCoste;
    private javax.swing.JLabel etiquetaProveedor;
    private javax.swing.JLabel etiquetaTelefonoContacto;
    private javax.swing.JLabel etiquetaTipo;
    private javax.swing.JLabel etiquetaUbicacion;
    private javax.swing.ButtonGroup grupoBotonesTipo;
    private javax.swing.JLabel labelMaterialCuadroCarretera;
    private javax.swing.JLabel labelMaterialCuadroCarretera1;
    private javax.swing.JLabel labelMaterialCuadroTrail;
    private javax.swing.JLabel labelTamanioRuedasTrail;
    private javax.swing.JLabel labelTitulo;
    private javax.swing.JPanel panelPrincipal;
    private javax.swing.JPanel panelTipo;
    private javax.swing.JPanel panelUbicacionPVP;
    private javax.swing.JRadioButton radioBotonCarretera;
    private javax.swing.JRadioButton radioBotonCrossCountry;
    private javax.swing.JRadioButton radioBotonDescenso;
    private javax.swing.JRadioButton radioBotonFatBike;
    private javax.swing.JRadioButton radioBotonTrail;
    private javax.swing.JSpinner spinnerFechaAlta;
    // End of variables declaration//GEN-END:variables
}
