/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * encuesta.java
 *
 * Created on 13-oct-2011, 14:02:02
 */

package aplicacionescritorio;

import javax.swing.JFrame;
import org.jdesktop.application.Action;

/**
 *
 * @author usuario
 */
public class encuesta extends javax.swing.JDialog {

    /** Creates new form encuesta */
    public encuesta(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
    }



    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        grpSexo = new javax.swing.ButtonGroup();
        lblProfesion = new javax.swing.JLabel();
        txtProfesion = new javax.swing.JTextField();
        pnlSexo = new javax.swing.JPanel();
        rdoHombre = new javax.swing.JRadioButton();
        rdoMujer = new javax.swing.JRadioButton();
        jPanel3 = new javax.swing.JPanel();
        pnlDeporte = new javax.swing.JScrollPane();
        lstDeporte = new javax.swing.JList();
        chkDeporte = new javax.swing.JCheckBox();
        lblNHermanos = new javax.swing.JLabel();
        spnHermanos = new javax.swing.JSpinner();
        lblEdad = new javax.swing.JLabel();
        cmbEdad = new javax.swing.JComboBox();
        lblAficion = new javax.swing.JLabel();
        lblCompras = new javax.swing.JLabel();
        sldCompras = new javax.swing.JSlider();
        lblTele = new javax.swing.JLabel();
        sldTelevision = new javax.swing.JSlider();
        lblCine = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        sldCine = new javax.swing.JSlider();
        btnAceptar = new javax.swing.JButton();
        btnCancelar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setName("Form"); // NOI18N

        org.jdesktop.application.ResourceMap resourceMap = org.jdesktop.application.Application.getInstance(aplicacionescritorio.AplicacionEscritorioApp.class).getContext().getResourceMap(encuesta.class);
        lblProfesion.setText(resourceMap.getString("lblProfesion.text")); // NOI18N
        lblProfesion.setName("lblProfesion"); // NOI18N

        txtProfesion.setText(resourceMap.getString("txtProfesion.text")); // NOI18N
        txtProfesion.setToolTipText(resourceMap.getString("txtProfesion.toolTipText")); // NOI18N
        txtProfesion.setName("txtProfesion"); // NOI18N

        pnlSexo.setBorder(javax.swing.BorderFactory.createTitledBorder(resourceMap.getString("pnlSexo.border.title"))); // NOI18N
        pnlSexo.setName("pnlSexo"); // NOI18N

        grpSexo.add(rdoHombre);
        rdoHombre.setText(resourceMap.getString("rdoHombre.text")); // NOI18N
        rdoHombre.setToolTipText(resourceMap.getString("rdoHombre.toolTipText")); // NOI18N
        rdoHombre.setName("rdoHombre"); // NOI18N

        grpSexo.add(rdoMujer);
        rdoMujer.setText(resourceMap.getString("rdoMujer.text")); // NOI18N
        rdoMujer.setToolTipText(resourceMap.getString("rdoMujer.toolTipText")); // NOI18N
        rdoMujer.setName("rdoMujer"); // NOI18N

        javax.swing.GroupLayout pnlSexoLayout = new javax.swing.GroupLayout(pnlSexo);
        pnlSexo.setLayout(pnlSexoLayout);
        pnlSexoLayout.setHorizontalGroup(
            pnlSexoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlSexoLayout.createSequentialGroup()
                .addContainerGap(105, Short.MAX_VALUE)
                .addComponent(rdoHombre)
                .addGap(84, 84, 84)
                .addComponent(rdoMujer)
                .addGap(32, 32, 32))
        );
        pnlSexoLayout.setVerticalGroup(
            pnlSexoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlSexoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                .addComponent(rdoMujer)
                .addComponent(rdoHombre, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        jPanel3.setBorder(javax.swing.BorderFactory.createTitledBorder(resourceMap.getString("jPanel3.border.title"))); // NOI18N
        jPanel3.setName("jPanel3"); // NOI18N

        pnlDeporte.setName("pnlDeporte"); // NOI18N

        lstDeporte.setModel(new javax.swing.AbstractListModel() {
            String[] strings = { "Tenis", "Fútbol", "Balonmano", "Atletismo", "Natación" };
            public int getSize() { return strings.length; }
            public Object getElementAt(int i) { return strings[i]; }
        });
        lstDeporte.setToolTipText(resourceMap.getString("lstDeporte.toolTipText")); // NOI18N
        lstDeporte.setName("lstDeporte"); // NOI18N
        pnlDeporte.setViewportView(lstDeporte);

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(pnlDeporte, javax.swing.GroupLayout.DEFAULT_SIZE, 148, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnlDeporte, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        chkDeporte.setText(resourceMap.getString("chkDeporte.text")); // NOI18N
        chkDeporte.setToolTipText(resourceMap.getString("chkDeporte.toolTipText")); // NOI18N
        chkDeporte.setName("chkDeporte"); // NOI18N

        lblNHermanos.setText(resourceMap.getString("lblNHermanos.text")); // NOI18N
        lblNHermanos.setName("lblNHermanos"); // NOI18N

        spnHermanos.setToolTipText(resourceMap.getString("spnHermanos.toolTipText")); // NOI18N
        spnHermanos.setName("spnHermanos"); // NOI18N

        lblEdad.setText(resourceMap.getString("lblEdad.text")); // NOI18N
        lblEdad.setName("lblEdad"); // NOI18N

        cmbEdad.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Entre 18 y 30", "Entre 31 y 50", "Entre 51 y 65", "Mayor de 65" }));
        cmbEdad.setToolTipText(resourceMap.getString("cmbEdad.toolTipText")); // NOI18N
        cmbEdad.setName("cmbEdad"); // NOI18N

        lblAficion.setFont(resourceMap.getFont("lblAficion.font")); // NOI18N
        lblAficion.setText(resourceMap.getString("lblAficion.text")); // NOI18N
        lblAficion.setName("lblAficion"); // NOI18N

        lblCompras.setText(resourceMap.getString("lblCompras.text")); // NOI18N
        lblCompras.setName("lblCompras"); // NOI18N

        sldCompras.setMajorTickSpacing(1);
        sldCompras.setMaximum(10);
        sldCompras.setMinimum(1);
        sldCompras.setMinorTickSpacing(1);
        sldCompras.setPaintLabels(true);
        sldCompras.setToolTipText(resourceMap.getString("sldCompras.toolTipText")); // NOI18N
        sldCompras.setValue(5);
        sldCompras.setName("sldCompras"); // NOI18N

        lblTele.setText(resourceMap.getString("lblTele.text")); // NOI18N
        lblTele.setName("lblTele"); // NOI18N

        sldTelevision.setMajorTickSpacing(1);
        sldTelevision.setMaximum(10);
        sldTelevision.setMinimum(1);
        sldTelevision.setMinorTickSpacing(1);
        sldTelevision.setPaintLabels(true);
        sldTelevision.setToolTipText(resourceMap.getString("sldTelevision.toolTipText")); // NOI18N
        sldTelevision.setValue(5);
        sldTelevision.setName("sldTelevision"); // NOI18N

        lblCine.setText(resourceMap.getString("lblCine.text")); // NOI18N
        lblCine.setName("lblCine"); // NOI18N

        jSeparator1.setName("jSeparator1"); // NOI18N

        sldCine.setMajorTickSpacing(1);
        sldCine.setMaximum(10);
        sldCine.setMinimum(1);
        sldCine.setMinorTickSpacing(1);
        sldCine.setPaintLabels(true);
        sldCine.setToolTipText(resourceMap.getString("sldCine.toolTipText")); // NOI18N
        sldCine.setValue(5);
        sldCine.setName("sldCine"); // NOI18N

        btnAceptar.setText(resourceMap.getString("btnAceptar.text")); // NOI18N
        btnAceptar.setName("btnAceptar"); // NOI18N

        javax.swing.ActionMap actionMap = org.jdesktop.application.Application.getInstance(aplicacionescritorio.AplicacionEscritorioApp.class).getContext().getActionMap(encuesta.class, this);
        btnCancelar.setAction(actionMap.get("cerrar")); // NOI18N
        btnCancelar.setText(resourceMap.getString("btnCancelar.text")); // NOI18N
        btnCancelar.setName("btnCancelar"); // NOI18N

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jSeparator1))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(lblProfesion)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtProfesion))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(chkDeporte)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(lblNHermanos)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(spnHermanos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(28, 28, 28)
                                .addComponent(lblEdad)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(cmbEdad, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addComponent(pnlSexo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addGap(24, 24, 24)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(lblCompras, javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addComponent(lblTele, javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addComponent(lblCine, javax.swing.GroupLayout.Alignment.TRAILING))
                                    .addGap(18, 18, 18)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(sldTelevision, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(sldCompras, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(sldCine, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGroup(layout.createSequentialGroup()
                                    .addGap(78, 78, 78)
                                    .addComponent(btnAceptar)
                                    .addGap(18, 18, 18)
                                    .addComponent(btnCancelar)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 91, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addComponent(lblAficion))))
                .addGap(75, 75, 75))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblProfesion)
                    .addComponent(txtProfesion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER, false)
                    .addComponent(lblNHermanos)
                    .addComponent(spnHermanos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblEdad)
                    .addComponent(cmbEdad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(pnlSexo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(chkDeporte)
                    .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 12, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblAficion)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(sldTelevision, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addComponent(lblCompras)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(sldCompras, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(28, 28, 28)
                        .addComponent(lblTele)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(sldCine, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(36, 36, 36)
                        .addComponent(lblCine)))
                .addGap(28, 28, 28)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnAceptar)
                    .addComponent(btnCancelar))
                .addGap(20, 20, 20))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
    * @param args the command line arguments
    */
   public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                encuesta dialog = new encuesta(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    @Action
    public void cerrar() {
            dispose();
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAceptar;
    private javax.swing.JButton btnCancelar;
    private javax.swing.JCheckBox chkDeporte;
    private javax.swing.JComboBox cmbEdad;
    private javax.swing.ButtonGroup grpSexo;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JLabel lblAficion;
    private javax.swing.JLabel lblCine;
    private javax.swing.JLabel lblCompras;
    private javax.swing.JLabel lblEdad;
    private javax.swing.JLabel lblNHermanos;
    private javax.swing.JLabel lblProfesion;
    private javax.swing.JLabel lblTele;
    private javax.swing.JList lstDeporte;
    private javax.swing.JScrollPane pnlDeporte;
    private javax.swing.JPanel pnlSexo;
    private javax.swing.JRadioButton rdoHombre;
    private javax.swing.JRadioButton rdoMujer;
    private javax.swing.JSlider sldCine;
    private javax.swing.JSlider sldCompras;
    private javax.swing.JSlider sldTelevision;
    private javax.swing.JSpinner spnHermanos;
    private javax.swing.JTextField txtProfesion;
    // End of variables declaration//GEN-END:variables

}
